
# This file is automatically generated, you probably don't want to edit this

banovaOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "banovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factors = NULL,
            random = NULL,
            bfType = "BF10",
            order = "nullModelTop",
            effects = FALSE,
            desc = FALSE,
            effectsType = "allModels",
            modelTerms = NULL,
            postHoc = list(),
            postHocCorr = TRUE,
            plotHz = NULL,
            plotLines = NULL,
            plotSep = NULL,
            plotCI = FALSE,
            ciWidth = 95,
            rScaleFixed = 0.5,
            rScaleRand = 1,
            sampling = "auto",
            nSamples = 10000, ...) {

            super$initialize(
                package='jsq',
                name='banova',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors)
            private$..random <- jmvcore::OptionVariables$new(
                "random",
                random,
                default=NULL)
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "nullModelTop",
                    "bestModelTop"),
                default="nullModelTop")
            private$..effects <- jmvcore::OptionBool$new(
                "effects",
                effects,
                default=FALSE)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..effectsType <- jmvcore::OptionList$new(
                "effectsType",
                effectsType,
                options=list(
                    "allModels",
                    "matchedModels"),
                default="allModels")
            private$..modelTerms <- jmvcore::OptionArray$new(
                "modelTerms",
                modelTerms,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "modelTerms",
                    NULL,
                    elements=list(
                        jmvcore::OptionArray$new(
                            "components",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "components",
                                NULL)),
                        jmvcore::OptionBool$new(
                            "isNuisance",
                            NULL))))
            private$..postHoc <- jmvcore::OptionVariables$new(
                "postHoc",
                postHoc,
                default=list())
            private$..postHocCorr <- jmvcore::OptionBool$new(
                "postHocCorr",
                postHocCorr,
                default=TRUE)
            private$..plotHz <- jmvcore::OptionVariable$new(
                "plotHz",
                plotHz,
                default=NULL)
            private$..plotLines <- jmvcore::OptionVariable$new(
                "plotLines",
                plotLines,
                default=NULL)
            private$..plotSep <- jmvcore::OptionVariable$new(
                "plotSep",
                plotSep,
                default=NULL)
            private$..plotCI <- jmvcore::OptionBool$new(
                "plotCI",
                plotCI,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..rScaleFixed <- jmvcore::OptionNumber$new(
                "rScaleFixed",
                rScaleFixed,
                default=0.5)
            private$..rScaleRand <- jmvcore::OptionNumber$new(
                "rScaleRand",
                rScaleRand,
                default=1)
            private$..sampling <- jmvcore::OptionList$new(
                "sampling",
                sampling,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..nSamples <- jmvcore::OptionInteger$new(
                "nSamples",
                nSamples,
                default=10000)

            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..random)
            self$.addOption(private$..bfType)
            self$.addOption(private$..order)
            self$.addOption(private$..effects)
            self$.addOption(private$..desc)
            self$.addOption(private$..effectsType)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..postHocCorr)
            self$.addOption(private$..plotHz)
            self$.addOption(private$..plotLines)
            self$.addOption(private$..plotSep)
            self$.addOption(private$..plotCI)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..rScaleFixed)
            self$.addOption(private$..rScaleRand)
            self$.addOption(private$..sampling)
            self$.addOption(private$..nSamples)
        }),
    active = list(
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        random = function() private$..random$value,
        bfType = function() private$..bfType$value,
        order = function() private$..order$value,
        effects = function() private$..effects$value,
        desc = function() private$..desc$value,
        effectsType = function() private$..effectsType$value,
        modelTerms = function() private$..modelTerms$value,
        postHoc = function() private$..postHoc$value,
        postHocCorr = function() private$..postHocCorr$value,
        plotHz = function() private$..plotHz$value,
        plotLines = function() private$..plotLines$value,
        plotSep = function() private$..plotSep$value,
        plotCI = function() private$..plotCI$value,
        ciWidth = function() private$..ciWidth$value,
        rScaleFixed = function() private$..rScaleFixed$value,
        rScaleRand = function() private$..rScaleRand$value,
        sampling = function() private$..sampling$value,
        nSamples = function() private$..nSamples$value),
    private = list(
        ..dep = NA,
        ..factors = NA,
        ..random = NA,
        ..bfType = NA,
        ..order = NA,
        ..effects = NA,
        ..desc = NA,
        ..effectsType = NA,
        ..modelTerms = NA,
        ..postHoc = NA,
        ..postHocCorr = NA,
        ..plotHz = NA,
        ..plotLines = NA,
        ..plotSep = NA,
        ..plotCI = NA,
        ..ciWidth = NA,
        ..rScaleFixed = NA,
        ..rScaleRand = NA,
        ..sampling = NA,
        ..nSamples = NA)
)

banovaResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        model_comparison = function() private$.items[["model_comparison"]],
        effects = function() private$.items[["effects"]],
        posthoc = function() private$.items[["posthoc"]],
        descriptivesObj = function() private$.items[["descriptivesObj"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian ANOVA",
                clearWith=list(
                    "dep",
                    "factors",
                    "random"))
            self$add(jmvcore::Table$new(
                options=options,
                name="model_comparison",
                columns=list(),
                clearWith=list(
                    "bfType",
                    "order",
                    "rScaleFixed",
                    "rScaleRand")))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                columns=list(),
                clearWith=list(
                    "bfType",
                    "effectsType",
                    "rScaleFixed",
                    "rScaleRand")))
            self$add(jmvcore::Array$new(
                options=options,
                name="posthoc",
                clearWith=list(
                    "rScaleFixed",
                    "rScaleRand"),
                template=jmvcore::Table$new(
                    options=options,
                    name="item",
                    columns=list())))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    descriptivesTable = function() private$.items[["descriptivesTable"]],
                    descriptivesPlot = function() private$.items[["descriptivesPlot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="descriptivesObj",
                            title="no title")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="descriptivesTable",
                            columns=list()))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="descriptivesPlot",
                            renderFun=".render"))}))$new(options=options))}))

banovaBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "banovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsq',
                name = 'banova',
                version = c(1,0,0),
                options = options,
                results = banovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bayesian ANOVA
#'
#' 
#' @param data .
#' @param dep .
#' @param factors .
#' @param random .
#' @param bfType .
#' @param order .
#' @param effects .
#' @param desc .
#' @param effectsType .
#' @param modelTerms .
#' @param postHoc .
#' @param postHocCorr .
#' @param plotHz .
#' @param plotLines .
#' @param plotSep .
#' @param plotCI .
#' @param ciWidth .
#' @param rScaleFixed .
#' @param rScaleRand .
#' @param sampling .
#' @param nSamples .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$model_comparison} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$posthoc} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$descriptivesObj$descriptivesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descriptivesObj$descriptivesPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$model_comparison$asDF}
#'
#' \code{as.data.frame(results$model_comparison)}
#'
#' @export
banova <- function(
    data,
    dep,
    factors,
    random = NULL,
    bfType = "BF10",
    order = "nullModelTop",
    effects = FALSE,
    desc = FALSE,
    effectsType = "allModels",
    modelTerms = NULL,
    postHoc = list(),
    postHocCorr = TRUE,
    plotHz = NULL,
    plotLines = NULL,
    plotSep = NULL,
    plotCI = FALSE,
    ciWidth = 95,
    rScaleFixed = 0.5,
    rScaleRand = 1,
    sampling = "auto",
    nSamples = 10000) {

    if ( ! requireNamespace('jmvcore'))
        stop('banova requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(random)) random <- jmvcore::resolveQuo(jmvcore::enquo(random))
    if ( ! missing(postHoc)) postHoc <- jmvcore::resolveQuo(jmvcore::enquo(postHoc))
    if ( ! missing(plotHz)) plotHz <- jmvcore::resolveQuo(jmvcore::enquo(plotHz))
    if ( ! missing(plotLines)) plotLines <- jmvcore::resolveQuo(jmvcore::enquo(plotLines))
    if ( ! missing(plotSep)) plotSep <- jmvcore::resolveQuo(jmvcore::enquo(plotSep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(random), random, NULL),
            `if`( ! missing(postHoc), postHoc, NULL),
            `if`( ! missing(plotHz), plotHz, NULL),
            `if`( ! missing(plotLines), plotLines, NULL),
            `if`( ! missing(plotSep), plotSep, NULL))


    options <- banovaOptions$new(
        dep = dep,
        factors = factors,
        random = random,
        bfType = bfType,
        order = order,
        effects = effects,
        desc = desc,
        effectsType = effectsType,
        modelTerms = modelTerms,
        postHoc = postHoc,
        postHocCorr = postHocCorr,
        plotHz = plotHz,
        plotLines = plotLines,
        plotSep = plotSep,
        plotCI = plotCI,
        ciWidth = ciWidth,
        rScaleFixed = rScaleFixed,
        rScaleRand = rScaleRand,
        sampling = sampling,
        nSamples = nSamples)

    results <- banovaResults$new(
        options = options)

    analysis <- banovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
