
# This file is automatically generated, you probably don't want to edit this

banovaRMOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "banovaRMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rm = list(
                list(label="RM Factor 1", levels=list(
                    "Level 1",
                    "Level 2"))),
            rmCells = NULL,
            bs = NULL,
            covs = NULL,
            bfType = "BF10",
            order = "nullModelTop",
            effects = FALSE,
            desc = FALSE,
            effectsType = "allModels",
            modelTerms = NULL,
            postHoc = NULL,
            postHocCorr = TRUE,
            plotHz = NULL,
            plotLines = NULL,
            plotSep = NULL,
            depLabel = "Dependent",
            plotCI = FALSE,
            ciWidth = 95,
            rScaleFixed = 0.5,
            rScaleRand = 1,
            rScaleCovs = 0.354,
            sampling = "auto",
            nSamples = 10000, ...) {

            super$initialize(
                package='jsq',
                name='banovaRM',
                requiresData=TRUE,
                ...)

            private$..rm <- jmvcore::OptionArray$new(
                "rm",
                rm,
                default=list(
                    list(label="RM Factor 1", levels=list(
                        "Level 1",
                        "Level 2"))),
                template=jmvcore::OptionGroup$new(
                    "rm",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "levels",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "levels",
                                NULL)))))
            private$..rmCells <- jmvcore::OptionArray$new(
                "rmCells",
                rmCells,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "rmCells",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "measure",
                            NULL),
                        jmvcore::OptionArray$new(
                            "cell",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "cell",
                                NULL)))))
            private$..bs <- jmvcore::OptionVariables$new(
                "bs",
                bs,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "nullModelTop",
                    "bestModelTop"),
                default="nullModelTop")
            private$..effects <- jmvcore::OptionBool$new(
                "effects",
                effects,
                default=FALSE)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..effectsType <- jmvcore::OptionList$new(
                "effectsType",
                effectsType,
                options=list(
                    "allModels",
                    "matchedModels"),
                default="allModels")
            private$..modelTerms <- jmvcore::OptionArray$new(
                "modelTerms",
                modelTerms,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "modelTerms",
                    NULL,
                    elements=list(
                        jmvcore::OptionArray$new(
                            "components",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "components",
                                NULL)),
                        jmvcore::OptionBool$new(
                            "isNuisance",
                            NULL))))
            private$..postHoc <- jmvcore::OptionArray$new(
                "postHoc",
                postHoc,
                template=jmvcore::OptionString$new(
                    "postHoc",
                    NULL),
                default=NULL)
            private$..postHocCorr <- jmvcore::OptionBool$new(
                "postHocCorr",
                postHocCorr,
                default=TRUE)
            private$..plotHz <- jmvcore::OptionString$new(
                "plotHz",
                plotHz)
            private$..plotLines <- jmvcore::OptionString$new(
                "plotLines",
                plotLines)
            private$..plotSep <- jmvcore::OptionString$new(
                "plotSep",
                plotSep)
            private$..depLabel <- jmvcore::OptionString$new(
                "depLabel",
                depLabel,
                default="Dependent")
            private$..plotCI <- jmvcore::OptionBool$new(
                "plotCI",
                plotCI,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..rScaleFixed <- jmvcore::OptionNumber$new(
                "rScaleFixed",
                rScaleFixed,
                default=0.5)
            private$..rScaleRand <- jmvcore::OptionNumber$new(
                "rScaleRand",
                rScaleRand,
                default=1)
            private$..rScaleCovs <- jmvcore::OptionNumber$new(
                "rScaleCovs",
                rScaleCovs,
                default=0.354)
            private$..sampling <- jmvcore::OptionList$new(
                "sampling",
                sampling,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..nSamples <- jmvcore::OptionInteger$new(
                "nSamples",
                nSamples,
                default=10000)

            self$.addOption(private$..rm)
            self$.addOption(private$..rmCells)
            self$.addOption(private$..bs)
            self$.addOption(private$..covs)
            self$.addOption(private$..bfType)
            self$.addOption(private$..order)
            self$.addOption(private$..effects)
            self$.addOption(private$..desc)
            self$.addOption(private$..effectsType)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..postHocCorr)
            self$.addOption(private$..plotHz)
            self$.addOption(private$..plotLines)
            self$.addOption(private$..plotSep)
            self$.addOption(private$..depLabel)
            self$.addOption(private$..plotCI)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..rScaleFixed)
            self$.addOption(private$..rScaleRand)
            self$.addOption(private$..rScaleCovs)
            self$.addOption(private$..sampling)
            self$.addOption(private$..nSamples)
        }),
    active = list(
        rm = function() private$..rm$value,
        rmCells = function() private$..rmCells$value,
        bs = function() private$..bs$value,
        covs = function() private$..covs$value,
        bfType = function() private$..bfType$value,
        order = function() private$..order$value,
        effects = function() private$..effects$value,
        desc = function() private$..desc$value,
        effectsType = function() private$..effectsType$value,
        modelTerms = function() private$..modelTerms$value,
        postHoc = function() private$..postHoc$value,
        postHocCorr = function() private$..postHocCorr$value,
        plotHz = function() private$..plotHz$value,
        plotLines = function() private$..plotLines$value,
        plotSep = function() private$..plotSep$value,
        depLabel = function() private$..depLabel$value,
        plotCI = function() private$..plotCI$value,
        ciWidth = function() private$..ciWidth$value,
        rScaleFixed = function() private$..rScaleFixed$value,
        rScaleRand = function() private$..rScaleRand$value,
        rScaleCovs = function() private$..rScaleCovs$value,
        sampling = function() private$..sampling$value,
        nSamples = function() private$..nSamples$value),
    private = list(
        ..rm = NA,
        ..rmCells = NA,
        ..bs = NA,
        ..covs = NA,
        ..bfType = NA,
        ..order = NA,
        ..effects = NA,
        ..desc = NA,
        ..effectsType = NA,
        ..modelTerms = NA,
        ..postHoc = NA,
        ..postHocCorr = NA,
        ..plotHz = NA,
        ..plotLines = NA,
        ..plotSep = NA,
        ..depLabel = NA,
        ..plotCI = NA,
        ..ciWidth = NA,
        ..rScaleFixed = NA,
        ..rScaleRand = NA,
        ..rScaleCovs = NA,
        ..sampling = NA,
        ..nSamples = NA)
)

banovaRMResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Repeated Measures ANOVA")}))

banovaRMBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "banovaRMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsq',
                name = 'banovaRM',
                version = c(1,0,0),
                options = options,
                results = banovaRMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bayesian Repeated Measures ANOVA
#'
#' 
#' @param data .
#' @param rm a list of lists, where each list describes the \code{label} (as a
#'   string) and the \code{levels} (as vector of strings) of a particular
#'   repeated measures factor
#' @param rmCells a list of lists, where each list decribes a repeated measure
#'   (as a string) from \code{data} defined as \code{measure} and the particular
#'   combination of levels from \code{rm} that it belongs to (as a vector of
#'   strings) defined as \code{cell}
#' @param bs a vector of strings naming the between subjects factors from
#'   \code{data}
#' @param covs a vector of strings naming the covariates from \code{data}.
#'   Variables must be numeric
#' @param bfType .
#' @param order .
#' @param effects .
#' @param desc .
#' @param effectsType .
#' @param modelTerms .
#' @param postHoc .
#' @param postHocCorr .
#' @param plotHz .
#' @param plotLines .
#' @param plotSep .
#' @param depLabel a string (default: 'Dependent') describing the label used
#'   for the dependent variable throughout the analysis
#' @param plotCI .
#' @param ciWidth .
#' @param rScaleFixed .
#' @param rScaleRand .
#' @param rScaleCovs .
#' @param sampling .
#' @param nSamples .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
banovaRM <- function(
    data,
    rm = list(
                list(label="RM Factor 1", levels=list(
                    "Level 1",
                    "Level 2"))),
    rmCells = NULL,
    bs = NULL,
    covs = NULL,
    bfType = "BF10",
    order = "nullModelTop",
    effects = FALSE,
    desc = FALSE,
    effectsType = "allModels",
    modelTerms = NULL,
    postHoc = NULL,
    postHocCorr = TRUE,
    plotHz,
    plotLines,
    plotSep,
    depLabel = "Dependent",
    plotCI = FALSE,
    ciWidth = 95,
    rScaleFixed = 0.5,
    rScaleRand = 1,
    rScaleCovs = 0.354,
    sampling = "auto",
    nSamples = 10000) {

    if ( ! requireNamespace('jmvcore'))
        stop('banovaRM requires jmvcore to be installed (restart may be required)')

    if ( ! missing(bs)) bs <- jmvcore::resolveQuo(jmvcore::enquo(bs))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(bs), bs, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in bs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- banovaRMOptions$new(
        rm = rm,
        rmCells = rmCells,
        bs = bs,
        covs = covs,
        bfType = bfType,
        order = order,
        effects = effects,
        desc = desc,
        effectsType = effectsType,
        modelTerms = modelTerms,
        postHoc = postHoc,
        postHocCorr = postHocCorr,
        plotHz = plotHz,
        plotLines = plotLines,
        plotSep = plotSep,
        depLabel = depLabel,
        plotCI = plotCI,
        ciWidth = ciWidth,
        rScaleFixed = rScaleFixed,
        rScaleRand = rScaleRand,
        rScaleCovs = rScaleCovs,
        sampling = sampling,
        nSamples = nSamples)

    results <- banovaRMResults$new(
        options = options)

    analysis <- banovaRMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
