
# This file is automatically generated, you probably don't want to edit this

bcontTablesOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bcontTablesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            layers = NULL,
            sampling = "poisson",
            hypothesis = "different",
            bfType = "BF10",
            oddsRatio = FALSE,
            oddsRatioCIWidth = 95,
            plotOddsRatio = FALSE,
            plotOddsRatioAddInfo = TRUE,
            priorWidth = 1, ...) {

            super$initialize(
                package='jsq',
                name='bcontTables',
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariables$new(
                "rows",
                rows)
            private$..cols <- jmvcore::OptionVariables$new(
                "cols",
                cols)
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                default=NULL)
            private$..layers <- jmvcore::OptionVariables$new(
                "layers",
                layers,
                default=NULL)
            private$..sampling <- jmvcore::OptionList$new(
                "sampling",
                sampling,
                options=list(
                    "poisson",
                    "joint",
                    "rowsFixed",
                    "colsFixed",
                    "hyper"),
                default="poisson")
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "different",
                    "oneGreater",
                    "twoGreater"),
                default="different")
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..oddsRatio <- jmvcore::OptionBool$new(
                "oddsRatio",
                oddsRatio,
                default=FALSE)
            private$..oddsRatioCIWidth <- jmvcore::OptionNumber$new(
                "oddsRatioCIWidth",
                oddsRatioCIWidth,
                default=95,
                min=50,
                max=99.9)
            private$..plotOddsRatio <- jmvcore::OptionBool$new(
                "plotOddsRatio",
                plotOddsRatio,
                default=FALSE)
            private$..plotOddsRatioAddInfo <- jmvcore::OptionBool$new(
                "plotOddsRatioAddInfo",
                plotOddsRatioAddInfo,
                default=TRUE)
            private$..priorWidth <- jmvcore::OptionNumber$new(
                "priorWidth",
                priorWidth,
                default=1)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..layers)
            self$.addOption(private$..sampling)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..bfType)
            self$.addOption(private$..oddsRatio)
            self$.addOption(private$..oddsRatioCIWidth)
            self$.addOption(private$..plotOddsRatio)
            self$.addOption(private$..plotOddsRatioAddInfo)
            self$.addOption(private$..priorWidth)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        layers = function() private$..layers$value,
        sampling = function() private$..sampling$value,
        hypothesis = function() private$..hypothesis$value,
        bfType = function() private$..bfType$value,
        oddsRatio = function() private$..oddsRatio$value,
        oddsRatioCIWidth = function() private$..oddsRatioCIWidth$value,
        plotOddsRatio = function() private$..plotOddsRatio$value,
        plotOddsRatioAddInfo = function() private$..plotOddsRatioAddInfo$value,
        priorWidth = function() private$..priorWidth$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..layers = NA,
        ..sampling = NA,
        ..hypothesis = NA,
        ..bfType = NA,
        ..oddsRatio = NA,
        ..oddsRatioCIWidth = NA,
        ..plotOddsRatio = NA,
        ..plotOddsRatioAddInfo = NA,
        ..priorWidth = NA)
)

bcontTablesResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Contingency Tables",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "layers"))}))

bcontTablesBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bcontTablesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsq',
                name = 'bcontTables',
                version = c(1,0,0),
                options = options,
                results = bcontTablesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bayesian Contingency Tables
#'
#' 
#' @param data .
#' @param rows .
#' @param cols .
#' @param counts .
#' @param layers .
#' @param sampling .
#' @param hypothesis .
#' @param bfType .
#' @param oddsRatio .
#' @param oddsRatioCIWidth .
#' @param plotOddsRatio .
#' @param plotOddsRatioAddInfo .
#' @param priorWidth .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
bcontTables <- function(
    data,
    rows,
    cols,
    counts = NULL,
    layers = NULL,
    sampling = "poisson",
    hypothesis = "different",
    bfType = "BF10",
    oddsRatio = FALSE,
    oddsRatioCIWidth = 95,
    plotOddsRatio = FALSE,
    plotOddsRatioAddInfo = TRUE,
    priorWidth = 1) {

    if ( ! requireNamespace('jmvcore'))
        stop('bcontTables requires jmvcore to be installed (restart may be required)')

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if ( ! missing(layers)) layers <- jmvcore::resolveQuo(jmvcore::enquo(layers))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL),
            `if`( ! missing(layers), layers, NULL))


    options <- bcontTablesOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        layers = layers,
        sampling = sampling,
        hypothesis = hypothesis,
        bfType = bfType,
        oddsRatio = oddsRatio,
        oddsRatioCIWidth = oddsRatioCIWidth,
        plotOddsRatio = plotOddsRatio,
        plotOddsRatioAddInfo = plotOddsRatioAddInfo,
        priorWidth = priorWidth)

    analysis <- bcontTablesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
