
# This file is automatically generated, you probably don't want to edit this

bcorrPairsOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bcorrPairsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            stat = "pearson",
            hypothesis = "corr",
            bfType = "BF10",
            priorWidth = 1,
            ci = FALSE,
            plotScat = FALSE,
            plotPP = FALSE,
            plotPPAddInfo = TRUE,
            plotRobust = FALSE,
            plotRobustAddInfo = TRUE,
            plotSeq = FALSE,
            missing = "perAnalysis", ...) {

            super$initialize(
                package='jsq',
                name='bcorrPairs',
                requiresData=TRUE,
                ...)

            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..stat <- jmvcore::OptionList$new(
                "stat",
                stat,
                options=list(
                    "pearson",
                    "kendall"),
                default="pearson")
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "corr",
                    "pos",
                    "neg"),
                default="corr")
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..priorWidth <- jmvcore::OptionNumber$new(
                "priorWidth",
                priorWidth,
                min=0,
                max=2,
                default=1)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..plotScat <- jmvcore::OptionBool$new(
                "plotScat",
                plotScat,
                default=FALSE)
            private$..plotPP <- jmvcore::OptionBool$new(
                "plotPP",
                plotPP,
                default=FALSE)
            private$..plotPPAddInfo <- jmvcore::OptionBool$new(
                "plotPPAddInfo",
                plotPPAddInfo,
                default=TRUE)
            private$..plotRobust <- jmvcore::OptionBool$new(
                "plotRobust",
                plotRobust,
                default=FALSE)
            private$..plotRobustAddInfo <- jmvcore::OptionBool$new(
                "plotRobustAddInfo",
                plotRobustAddInfo,
                default=TRUE)
            private$..plotSeq <- jmvcore::OptionBool$new(
                "plotSeq",
                plotSeq,
                default=FALSE)
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "perAnalysis",
                    "listwise"),
                default="perAnalysis")

            self$.addOption(private$..pairs)
            self$.addOption(private$..stat)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..bfType)
            self$.addOption(private$..priorWidth)
            self$.addOption(private$..ci)
            self$.addOption(private$..plotScat)
            self$.addOption(private$..plotPP)
            self$.addOption(private$..plotPPAddInfo)
            self$.addOption(private$..plotRobust)
            self$.addOption(private$..plotRobustAddInfo)
            self$.addOption(private$..plotSeq)
            self$.addOption(private$..missing)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        stat = function() private$..stat$value,
        hypothesis = function() private$..hypothesis$value,
        bfType = function() private$..bfType$value,
        priorWidth = function() private$..priorWidth$value,
        ci = function() private$..ci$value,
        plotScat = function() private$..plotScat$value,
        plotPP = function() private$..plotPP$value,
        plotPPAddInfo = function() private$..plotPPAddInfo$value,
        plotRobust = function() private$..plotRobust$value,
        plotRobustAddInfo = function() private$..plotRobustAddInfo$value,
        plotSeq = function() private$..plotSeq$value,
        missing = function() private$..missing$value),
    private = list(
        ..pairs = NA,
        ..stat = NA,
        ..hypothesis = NA,
        ..bfType = NA,
        ..priorWidth = NA,
        ..ci = NA,
        ..plotScat = NA,
        ..plotPP = NA,
        ..plotPPAddInfo = NA,
        ..plotRobust = NA,
        ..plotRobustAddInfo = NA,
        ..plotSeq = NA,
        ..missing = NA)
)

bcorrPairsResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Correlation Pairs",
                clearWith=list(
                    "pairs"))}))

bcorrPairsBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bcorrPairsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsq',
                name = 'bcorrPairs',
                version = c(1,0,0),
                options = options,
                results = bcorrPairsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bayesian Correlation Pairs
#'
#' 
#' @param data .
#' @param pairs .
#' @param stat .
#' @param hypothesis .
#' @param bfType .
#' @param priorWidth .
#' @param ci .
#' @param plotScat .
#' @param plotPP .
#' @param plotPPAddInfo .
#' @param plotRobust .
#' @param plotRobustAddInfo .
#' @param plotSeq .
#' @param missing .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
bcorrPairs <- function(
    data,
    pairs,
    stat = "pearson",
    hypothesis = "corr",
    bfType = "BF10",
    priorWidth = 1,
    ci = FALSE,
    plotScat = FALSE,
    plotPP = FALSE,
    plotPPAddInfo = TRUE,
    plotRobust = FALSE,
    plotRobustAddInfo = TRUE,
    plotSeq = FALSE,
    missing = "perAnalysis") {

    if ( ! requireNamespace('jmvcore'))
        stop('bcorrPairs requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- bcorrPairsOptions$new(
        pairs = pairs,
        stat = stat,
        hypothesis = hypothesis,
        bfType = bfType,
        priorWidth = priorWidth,
        ci = ci,
        plotScat = plotScat,
        plotPP = plotPP,
        plotPPAddInfo = plotPPAddInfo,
        plotRobust = plotRobust,
        plotRobustAddInfo = plotRobustAddInfo,
        plotSeq = plotSeq,
        missing = missing)

    results <- bcorrPairsResults$new(
        options = options)

    analysis <- bcorrPairsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
