
# This file is automatically generated, you probably don't want to edit this

blinRegOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "blinRegOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            wls = NULL,
            bfType = "BF10",
            order = "nullModelTop",
            desc = FALSE,
            postSumm = FALSE,
            postSummModel = "best",
            omitIntercept = FALSE,
            plotSumm = FALSE,
            ciWidth = 95,
            limitModels = "limited",
            limitModelsN = 10,
            modelTerms = NULL,
            plotCoefInc = FALSE,
            plotCoef = FALSE,
            plotResVFit = FALSE,
            plotOdds = FALSE,
            modelVSize = FALSE,
            modelProbs = FALSE,
            prior = "JZS",
            jzsS = 0.354,
            hAlpha = 3,
            modelPrior = "unif",
            bernP = 0.5,
            betaA = 1,
            betaB = 1,
            sampling = "BAS",
            basNModels = 0,
            mcmcN = 0,
            ciN = 1000, ...) {

            super$initialize(
                package="jsq",
                name="blinReg",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..wls <- jmvcore::OptionVariable$new(
                "wls",
                wls,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "nullModelTop",
                    "bestModelTop"),
                default="nullModelTop")
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..postSumm <- jmvcore::OptionBool$new(
                "postSumm",
                postSumm,
                default=FALSE)
            private$..postSummModel <- jmvcore::OptionList$new(
                "postSummModel",
                postSummModel,
                options=list(
                    "best",
                    "complex",
                    "median",
                    "averaged"),
                default="best")
            private$..omitIntercept <- jmvcore::OptionBool$new(
                "omitIntercept",
                omitIntercept,
                default=FALSE)
            private$..plotSumm <- jmvcore::OptionBool$new(
                "plotSumm",
                plotSumm,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..limitModels <- jmvcore::OptionList$new(
                "limitModels",
                limitModels,
                options=list(
                    "limited",
                    "unlimited"),
                default="limited")
            private$..limitModelsN <- jmvcore::OptionInteger$new(
                "limitModelsN",
                limitModelsN,
                default=10,
                min=1)
            private$..modelTerms <- jmvcore::OptionArray$new(
                "modelTerms",
                modelTerms,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "modelTerms",
                    NULL,
                    elements=list(
                        jmvcore::OptionTerm$new(
                            "components",
                            NULL),
                        jmvcore::OptionBool$new(
                            "isNuisance",
                            NULL))))
            private$..plotCoefInc <- jmvcore::OptionBool$new(
                "plotCoefInc",
                plotCoefInc,
                default=FALSE)
            private$..plotCoef <- jmvcore::OptionBool$new(
                "plotCoef",
                plotCoef,
                default=FALSE)
            private$..plotResVFit <- jmvcore::OptionBool$new(
                "plotResVFit",
                plotResVFit,
                default=FALSE)
            private$..plotOdds <- jmvcore::OptionBool$new(
                "plotOdds",
                plotOdds,
                default=FALSE)
            private$..modelVSize <- jmvcore::OptionBool$new(
                "modelVSize",
                modelVSize,
                default=FALSE)
            private$..modelProbs <- jmvcore::OptionBool$new(
                "modelProbs",
                modelProbs,
                default=FALSE)
            private$..prior <- jmvcore::OptionList$new(
                "prior",
                prior,
                options=list(
                    "AIC",
                    "BIC",
                    "EB-global",
                    "EB-local",
                    "g-prior",
                    "hyper-g",
                    "hyper-g-laplace",
                    "hyper-g-n",
                    "JZS"),
                default="JZS")
            private$..jzsS <- jmvcore::OptionNumber$new(
                "jzsS",
                jzsS,
                default=0.354)
            private$..hAlpha <- jmvcore::OptionNumber$new(
                "hAlpha",
                hAlpha,
                default=3)
            private$..modelPrior <- jmvcore::OptionList$new(
                "modelPrior",
                modelPrior,
                options=list(
                    "beta",
                    "bern",
                    "unif"),
                default="unif")
            private$..bernP <- jmvcore::OptionNumber$new(
                "bernP",
                bernP,
                default=0.5)
            private$..betaA <- jmvcore::OptionNumber$new(
                "betaA",
                betaA,
                default=1)
            private$..betaB <- jmvcore::OptionNumber$new(
                "betaB",
                betaB,
                default=1)
            private$..sampling <- jmvcore::OptionList$new(
                "sampling",
                sampling,
                options=list(
                    "BAS",
                    "MCMC"),
                default="BAS")
            private$..basNModels <- jmvcore::OptionInteger$new(
                "basNModels",
                basNModels,
                min=0,
                default=0)
            private$..mcmcN <- jmvcore::OptionInteger$new(
                "mcmcN",
                mcmcN,
                default=0,
                min=0)
            private$..ciN <- jmvcore::OptionInteger$new(
                "ciN",
                ciN,
                min=0,
                default=1000)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..wls)
            self$.addOption(private$..bfType)
            self$.addOption(private$..order)
            self$.addOption(private$..desc)
            self$.addOption(private$..postSumm)
            self$.addOption(private$..postSummModel)
            self$.addOption(private$..omitIntercept)
            self$.addOption(private$..plotSumm)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..limitModels)
            self$.addOption(private$..limitModelsN)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..plotCoefInc)
            self$.addOption(private$..plotCoef)
            self$.addOption(private$..plotResVFit)
            self$.addOption(private$..plotOdds)
            self$.addOption(private$..modelVSize)
            self$.addOption(private$..modelProbs)
            self$.addOption(private$..prior)
            self$.addOption(private$..jzsS)
            self$.addOption(private$..hAlpha)
            self$.addOption(private$..modelPrior)
            self$.addOption(private$..bernP)
            self$.addOption(private$..betaA)
            self$.addOption(private$..betaB)
            self$.addOption(private$..sampling)
            self$.addOption(private$..basNModels)
            self$.addOption(private$..mcmcN)
            self$.addOption(private$..ciN)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        wls = function() private$..wls$value,
        bfType = function() private$..bfType$value,
        order = function() private$..order$value,
        desc = function() private$..desc$value,
        postSumm = function() private$..postSumm$value,
        postSummModel = function() private$..postSummModel$value,
        omitIntercept = function() private$..omitIntercept$value,
        plotSumm = function() private$..plotSumm$value,
        ciWidth = function() private$..ciWidth$value,
        limitModels = function() private$..limitModels$value,
        limitModelsN = function() private$..limitModelsN$value,
        modelTerms = function() private$..modelTerms$value,
        plotCoefInc = function() private$..plotCoefInc$value,
        plotCoef = function() private$..plotCoef$value,
        plotResVFit = function() private$..plotResVFit$value,
        plotOdds = function() private$..plotOdds$value,
        modelVSize = function() private$..modelVSize$value,
        modelProbs = function() private$..modelProbs$value,
        prior = function() private$..prior$value,
        jzsS = function() private$..jzsS$value,
        hAlpha = function() private$..hAlpha$value,
        modelPrior = function() private$..modelPrior$value,
        bernP = function() private$..bernP$value,
        betaA = function() private$..betaA$value,
        betaB = function() private$..betaB$value,
        sampling = function() private$..sampling$value,
        basNModels = function() private$..basNModels$value,
        mcmcN = function() private$..mcmcN$value,
        ciN = function() private$..ciN$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..wls = NA,
        ..bfType = NA,
        ..order = NA,
        ..desc = NA,
        ..postSumm = NA,
        ..postSummModel = NA,
        ..omitIntercept = NA,
        ..plotSumm = NA,
        ..ciWidth = NA,
        ..limitModels = NA,
        ..limitModelsN = NA,
        ..modelTerms = NA,
        ..plotCoefInc = NA,
        ..plotCoef = NA,
        ..plotResVFit = NA,
        ..plotOdds = NA,
        ..modelVSize = NA,
        ..modelProbs = NA,
        ..prior = NA,
        ..jzsS = NA,
        ..hAlpha = NA,
        ..modelPrior = NA,
        ..bernP = NA,
        ..betaA = NA,
        ..betaB = NA,
        ..sampling = NA,
        ..basNModels = NA,
        ..mcmcN = NA,
        ..ciN = NA)
)

blinRegResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "blinRegResults",
    inherit = jmvcore::Group,
    active = list(
        regressionTable = function() private$.items[["regressionTable"]],
        posteriorSummary = function() private$.items[["posteriorSummary"]],
        descriptivesTable = function() private$.items[["descriptivesTable"]],
        inferentialPlots = function() private$.items[["inferentialPlots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Linear Regression",
                clearWith=list(
                    "deps",
                    "covs",
                    "wls"))
            self$add(jmvcore::Table$new(
                options=options,
                name="regressionTable",
                columns=list(),
                clearWith=NULL))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    posteriorSummaryTable = function() private$.items[["posteriorSummaryTable"]],
                    posteriorSummaryPlot = function() private$.items[["posteriorSummaryPlot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="posteriorSummary",
                            title="no title")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="posteriorSummaryTable",
                            columns=list(),
                            clearWith=NULL))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="posteriorSummaryPlot",
                            renderFun=".render",
                            clearWith=NULL))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="descriptivesTable",
                columns=list(),
                clearWith=NULL))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    PosteriorPlotModels = function() private$.items[["PosteriorPlotModels"]],
                    ResidualsVsFittedPlot = function() private$.items[["ResidualsVsFittedPlot"]],
                    ModelProbabilitiesPlot = function() private$.items[["ModelProbabilitiesPlot"]],
                    ModelComplexityPlot = function() private$.items[["ModelComplexityPlot"]],
                    InclusionProbabilitiesPlot = function() private$.items[["InclusionProbabilitiesPlot"]],
                    coefficentsPlots = function() private$.items[["coefficentsPlots"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="inferentialPlots",
                            title="no title")
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="PosteriorPlotModels",
                            renderFun=".render",
                            clearWith=NULL))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="ResidualsVsFittedPlot",
                            renderFun=".render",
                            clearWith=NULL))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="ModelProbabilitiesPlot",
                            renderFun=".render",
                            clearWith=NULL))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="ModelComplexityPlot",
                            renderFun=".render",
                            clearWith=NULL))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="InclusionProbabilitiesPlot",
                            renderFun=".render",
                            clearWith=NULL))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="coefficentsPlots",
                            clearWith=NULL,
                            template=R6::R6Class(
                                inherit = jmvcore::Group,
                                active = list(
                                    PosteriorCoefficients = function() private$.items[["PosteriorCoefficients"]]),
                                private = list(),
                                public=list(
                                    initialize=function(options) {
                                        super$initialize(
                                            options=options,
                                            name="plotGroups",
                                            title="no title")
                                        self$add(jmvcore::Image$new(
                                            options=options,
                                            name="PosteriorCoefficients",
                                            renderFun=".render",
                                            clearWith=NULL))}))$new(options=options)))}))$new(options=options))}))

blinRegBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "blinRegBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jsq",
                name = "blinReg",
                version = c(1,0,0),
                options = options,
                results = blinRegResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bayesian Linear Regression
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param wls .
#' @param bfType .
#' @param order .
#' @param desc .
#' @param postSumm .
#' @param postSummModel .
#' @param omitIntercept .
#' @param plotSumm .
#' @param ciWidth .
#' @param limitModels .
#' @param limitModelsN .
#' @param modelTerms .
#' @param plotCoefInc .
#' @param plotCoef .
#' @param plotResVFit .
#' @param plotOdds .
#' @param modelVSize .
#' @param modelProbs .
#' @param prior .
#' @param jzsS .
#' @param hAlpha .
#' @param modelPrior .
#' @param bernP .
#' @param betaA .
#' @param betaB .
#' @param sampling .
#' @param basNModels .
#' @param mcmcN .
#' @param ciN .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$regressionTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$posteriorSummary$posteriorSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$posteriorSummary$posteriorSummaryPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$descriptivesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$inferentialPlots$PosteriorPlotModels} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$inferentialPlots$ResidualsVsFittedPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$inferentialPlots$ModelProbabilitiesPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$inferentialPlots$ModelComplexityPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$inferentialPlots$InclusionProbabilitiesPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$inferentialPlots$coefficentsPlots} \tab \tab \tab \tab \tab an array \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$regressionTable$asDF}
#'
#' \code{as.data.frame(results$regressionTable)}
#'
#' @export
blinReg <- function(
    data,
    dep,
    covs,
    wls = NULL,
    bfType = "BF10",
    order = "nullModelTop",
    desc = FALSE,
    postSumm = FALSE,
    postSummModel = "best",
    omitIntercept = FALSE,
    plotSumm = FALSE,
    ciWidth = 95,
    limitModels = "limited",
    limitModelsN = 10,
    modelTerms = NULL,
    plotCoefInc = FALSE,
    plotCoef = FALSE,
    plotResVFit = FALSE,
    plotOdds = FALSE,
    modelVSize = FALSE,
    modelProbs = FALSE,
    prior = "JZS",
    jzsS = 0.354,
    hAlpha = 3,
    modelPrior = "unif",
    bernP = 0.5,
    betaA = 1,
    betaB = 1,
    sampling = "BAS",
    basNModels = 0,
    mcmcN = 0,
    ciN = 1000) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("blinReg requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(wls)) wls <- jmvcore::resolveQuo(jmvcore::enquo(wls))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(wls), wls, NULL))


    options <- blinRegOptions$new(
        dep = dep,
        covs = covs,
        wls = wls,
        bfType = bfType,
        order = order,
        desc = desc,
        postSumm = postSumm,
        postSummModel = postSummModel,
        omitIntercept = omitIntercept,
        plotSumm = plotSumm,
        ciWidth = ciWidth,
        limitModels = limitModels,
        limitModelsN = limitModelsN,
        modelTerms = modelTerms,
        plotCoefInc = plotCoefInc,
        plotCoef = plotCoef,
        plotResVFit = plotResVFit,
        plotOdds = plotOdds,
        modelVSize = modelVSize,
        modelProbs = modelProbs,
        prior = prior,
        jzsS = jzsS,
        hAlpha = hAlpha,
        modelPrior = modelPrior,
        bernP = bernP,
        betaA = betaA,
        betaB = betaB,
        sampling = sampling,
        basNModels = basNModels,
        mcmcN = mcmcN,
        ciN = ciN)

    analysis <- blinRegClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

