
# This file is automatically generated, you probably don't want to edit this

blogLinearOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "blogLinearOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = NULL,
            counts = NULL,
            bfType = "BF10",
            priorShape = -1,
            priorScale = 0,
            maxModels = 2,
            postProbCutOff = 0.1,
            modelTerms = NULL,
            est = FALSE,
            ci = FALSE,
            ciWidth = 95,
            sub = FALSE,
            subNo = 1,
            subEst = FALSE,
            subCI = FALSE,
            subCIWidth = 95,
            sampling = "auto",
            nSamples = 10000, ...) {

            super$initialize(
                package='jsq',
                name='blogLinear',
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors)
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                default=NULL)
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..priorShape <- jmvcore::OptionNumber$new(
                "priorShape",
                priorShape,
                default=-1)
            private$..priorScale <- jmvcore::OptionNumber$new(
                "priorScale",
                priorScale,
                default=0)
            private$..maxModels <- jmvcore::OptionInteger$new(
                "maxModels",
                maxModels,
                default=2)
            private$..postProbCutOff <- jmvcore::OptionNumber$new(
                "postProbCutOff",
                postProbCutOff,
                default=0.1)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)
            private$..est <- jmvcore::OptionBool$new(
                "est",
                est,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..sub <- jmvcore::OptionBool$new(
                "sub",
                sub,
                default=FALSE)
            private$..subNo <- jmvcore::OptionInteger$new(
                "subNo",
                subNo,
                default=1)
            private$..subEst <- jmvcore::OptionBool$new(
                "subEst",
                subEst,
                default=FALSE)
            private$..subCI <- jmvcore::OptionBool$new(
                "subCI",
                subCI,
                default=FALSE)
            private$..subCIWidth <- jmvcore::OptionNumber$new(
                "subCIWidth",
                subCIWidth,
                default=95,
                min=50,
                max=99.9)
            private$..sampling <- jmvcore::OptionList$new(
                "sampling",
                sampling,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..nSamples <- jmvcore::OptionInteger$new(
                "nSamples",
                nSamples,
                default=10000)

            self$.addOption(private$..factors)
            self$.addOption(private$..counts)
            self$.addOption(private$..bfType)
            self$.addOption(private$..priorShape)
            self$.addOption(private$..priorScale)
            self$.addOption(private$..maxModels)
            self$.addOption(private$..postProbCutOff)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..est)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..sub)
            self$.addOption(private$..subNo)
            self$.addOption(private$..subEst)
            self$.addOption(private$..subCI)
            self$.addOption(private$..subCIWidth)
            self$.addOption(private$..sampling)
            self$.addOption(private$..nSamples)
        }),
    active = list(
        factors = function() private$..factors$value,
        counts = function() private$..counts$value,
        bfType = function() private$..bfType$value,
        priorShape = function() private$..priorShape$value,
        priorScale = function() private$..priorScale$value,
        maxModels = function() private$..maxModels$value,
        postProbCutOff = function() private$..postProbCutOff$value,
        modelTerms = function() private$..modelTerms$value,
        est = function() private$..est$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        sub = function() private$..sub$value,
        subNo = function() private$..subNo$value,
        subEst = function() private$..subEst$value,
        subCI = function() private$..subCI$value,
        subCIWidth = function() private$..subCIWidth$value,
        sampling = function() private$..sampling$value,
        nSamples = function() private$..nSamples$value),
    private = list(
        ..factors = NA,
        ..counts = NA,
        ..bfType = NA,
        ..priorShape = NA,
        ..priorScale = NA,
        ..maxModels = NA,
        ..postProbCutOff = NA,
        ..modelTerms = NA,
        ..est = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..sub = NA,
        ..subNo = NA,
        ..subEst = NA,
        ..subCI = NA,
        ..subCIWidth = NA,
        ..sampling = NA,
        ..nSamples = NA)
)

blogLinearResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Log-Linear Regression",
                clearWith=list(
                    "factors",
                    "counts"))}))

blogLinearBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "blogLinearBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsq',
                name = 'blogLinear',
                version = c(1,0,0),
                options = options,
                results = blogLinearResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bayesian Log-Linear Regression
#'
#' 
#' @param data .
#' @param factors .
#' @param counts .
#' @param bfType .
#' @param priorShape .
#' @param priorScale .
#' @param maxModels .
#' @param postProbCutOff .
#' @param modelTerms .
#' @param est .
#' @param ci .
#' @param ciWidth .
#' @param sub .
#' @param subNo .
#' @param subEst .
#' @param subCI .
#' @param subCIWidth .
#' @param sampling .
#' @param nSamples .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
blogLinear <- function(
    data,
    factors,
    counts = NULL,
    bfType = "BF10",
    priorShape = -1,
    priorScale = 0,
    maxModels = 2,
    postProbCutOff = 0.1,
    modelTerms = NULL,
    est = FALSE,
    ci = FALSE,
    ciWidth = 95,
    sub = FALSE,
    subNo = 1,
    subEst = FALSE,
    subCI = FALSE,
    subCIWidth = 95,
    sampling = "auto",
    nSamples = 10000) {

    if ( ! requireNamespace('jmvcore'))
        stop('blogLinear requires jmvcore to be installed (restart may be required)')

    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(counts), counts, NULL))

    if (inherits(modelTerms, 'formula')) modelTerms <- jmvcore::decomposeFormula(modelTerms)

    options <- blogLinearOptions$new(
        factors = factors,
        counts = counts,
        bfType = bfType,
        priorShape = priorShape,
        priorScale = priorScale,
        maxModels = maxModels,
        postProbCutOff = postProbCutOff,
        modelTerms = modelTerms,
        est = est,
        ci = ci,
        ciWidth = ciWidth,
        sub = sub,
        subNo = subNo,
        subEst = subEst,
        subCI = subCI,
        subCIWidth = subCIWidth,
        sampling = sampling,
        nSamples = nSamples)

    analysis <- blogLinearClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
