
# This file is automatically generated, you probably don't want to edit this

bpropTest2Options <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bpropTest2Options",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            testValue = 0.5,
            hypothesis = "different",
            bfType = "BF10",
            plotPP = FALSE,
            plotPPAddInfo = TRUE,
            plotSeq = FALSE,
            priorA = 1,
            priorB = 1, ...) {

            super$initialize(
                package='jsq',
                name='bpropTest2',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal"))
            private$..testValue <- jmvcore::OptionNumber$new(
                "testValue",
                testValue,
                min=0,
                max=1,
                default=0.5)
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "different",
                    "greater",
                    "less"),
                default="different")
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..plotPP <- jmvcore::OptionBool$new(
                "plotPP",
                plotPP,
                default=FALSE)
            private$..plotPPAddInfo <- jmvcore::OptionBool$new(
                "plotPPAddInfo",
                plotPPAddInfo,
                default=TRUE)
            private$..plotSeq <- jmvcore::OptionBool$new(
                "plotSeq",
                plotSeq,
                default=FALSE)
            private$..priorA <- jmvcore::OptionNumber$new(
                "priorA",
                priorA,
                min=0.1,
                max=9999,
                default=1)
            private$..priorB <- jmvcore::OptionNumber$new(
                "priorB",
                priorB,
                min=0.1,
                max=9999,
                default=1)

            self$.addOption(private$..vars)
            self$.addOption(private$..testValue)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..bfType)
            self$.addOption(private$..plotPP)
            self$.addOption(private$..plotPPAddInfo)
            self$.addOption(private$..plotSeq)
            self$.addOption(private$..priorA)
            self$.addOption(private$..priorB)
        }),
    active = list(
        vars = function() private$..vars$value,
        testValue = function() private$..testValue$value,
        hypothesis = function() private$..hypothesis$value,
        bfType = function() private$..bfType$value,
        plotPP = function() private$..plotPP$value,
        plotPPAddInfo = function() private$..plotPPAddInfo$value,
        plotSeq = function() private$..plotSeq$value,
        priorA = function() private$..priorA$value,
        priorB = function() private$..priorB$value),
    private = list(
        ..vars = NA,
        ..testValue = NA,
        ..hypothesis = NA,
        ..bfType = NA,
        ..plotPP = NA,
        ..plotPPAddInfo = NA,
        ..plotSeq = NA,
        ..priorA = NA,
        ..priorB = NA)
)

bpropTest2Results <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Proportion Test (2 Outcomes)",
                clearWith=list(
                    "vars"))}))

bpropTest2Base <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bpropTest2Base",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsq',
                name = 'bpropTest2',
                version = c(1,0,0),
                options = options,
                results = bpropTest2Results$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bayesian Proportion Test
#'
#' 
#' @param data .
#' @param vars .
#' @param testValue .
#' @param hypothesis .
#' @param bfType .
#' @param plotPP .
#' @param plotPPAddInfo .
#' @param plotSeq .
#' @param priorA .
#' @param priorB .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
bpropTest2 <- function(
    data,
    vars,
    testValue = 0.5,
    hypothesis = "different",
    bfType = "BF10",
    plotPP = FALSE,
    plotPPAddInfo = TRUE,
    plotSeq = FALSE,
    priorA = 1,
    priorB = 1) {

    if ( ! requireNamespace('jmvcore'))
        stop('bpropTest2 requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- bpropTest2Options$new(
        vars = vars,
        testValue = testValue,
        hypothesis = hypothesis,
        bfType = bfType,
        plotPP = plotPP,
        plotPPAddInfo = plotPPAddInfo,
        plotSeq = plotSeq,
        priorA = priorA,
        priorB = priorB)

    analysis <- bpropTest2Class$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
