
# This file is automatically generated, you probably don't want to edit this

bttestPSOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestPSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            hypothesis = "different",
            bfType = "BF10",
            desc = FALSE,
            plotPP = FALSE,
            plotPPAddInfo = TRUE,
            plotRobust = FALSE,
            plotRobustAddInfo = TRUE,
            plotSeq = FALSE,
            plotSeqRobust = FALSE,
            plotDesc = FALSE,
            plotDescCI = 95,
            missing = "perAnalysis",
            priorType = "default",
            priorWidth = 0.707,
            infoShape = "cauchy",
            infoCL = 0,
            infoCS = 0.707,
            infoNL = 0,
            infoNS = 0.707,
            infoTL = 0,
            infoTS = 0.707,
            infoTDf = 1,
            plotWidth = 320,
            plotHeight = 240, ...) {

            super$initialize(
                package='jsq',
                name='bttestPS',
                requiresData=TRUE,
                ...)

            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "different",
                    "oneGreater",
                    "twoGreater"),
                default="different")
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..plotPP <- jmvcore::OptionBool$new(
                "plotPP",
                plotPP,
                default=FALSE)
            private$..plotPPAddInfo <- jmvcore::OptionBool$new(
                "plotPPAddInfo",
                plotPPAddInfo,
                default=TRUE)
            private$..plotRobust <- jmvcore::OptionBool$new(
                "plotRobust",
                plotRobust,
                default=FALSE)
            private$..plotRobustAddInfo <- jmvcore::OptionBool$new(
                "plotRobustAddInfo",
                plotRobustAddInfo,
                default=TRUE)
            private$..plotSeq <- jmvcore::OptionBool$new(
                "plotSeq",
                plotSeq,
                default=FALSE)
            private$..plotSeqRobust <- jmvcore::OptionBool$new(
                "plotSeqRobust",
                plotSeqRobust,
                default=FALSE)
            private$..plotDesc <- jmvcore::OptionBool$new(
                "plotDesc",
                plotDesc,
                default=FALSE)
            private$..plotDescCI <- jmvcore::OptionNumber$new(
                "plotDescCI",
                plotDescCI,
                default=95,
                min=50,
                max=99.9)
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "perAnalysis",
                    "excludeListwise"),
                default="perAnalysis")
            private$..priorType <- jmvcore::OptionList$new(
                "priorType",
                priorType,
                options=list(
                    "default",
                    "info"),
                default="default")
            private$..priorWidth <- jmvcore::OptionNumber$new(
                "priorWidth",
                priorWidth,
                default=0.707,
                min=0,
                max=2)
            private$..infoShape <- jmvcore::OptionList$new(
                "infoShape",
                infoShape,
                options=list(
                    "cauchy",
                    "normal",
                    "t"),
                default="cauchy")
            private$..infoCL <- jmvcore::OptionNumber$new(
                "infoCL",
                infoCL,
                default=0)
            private$..infoCS <- jmvcore::OptionNumber$new(
                "infoCS",
                infoCS,
                default=0.707,
                min=0,
                max=2)
            private$..infoNL <- jmvcore::OptionNumber$new(
                "infoNL",
                infoNL,
                default=0)
            private$..infoNS <- jmvcore::OptionNumber$new(
                "infoNS",
                infoNS,
                default=0.707)
            private$..infoTL <- jmvcore::OptionNumber$new(
                "infoTL",
                infoTL,
                default=0)
            private$..infoTS <- jmvcore::OptionNumber$new(
                "infoTS",
                infoTS,
                default=0.707)
            private$..infoTDf <- jmvcore::OptionNumber$new(
                "infoTDf",
                infoTDf,
                default=1)
            private$..plotWidth <- jmvcore::OptionInteger$new(
                "plotWidth",
                plotWidth,
                default=320,
                hidden=TRUE)
            private$..plotHeight <- jmvcore::OptionInteger$new(
                "plotHeight",
                plotHeight,
                default=240,
                hidden=TRUE)

            self$.addOption(private$..pairs)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..bfType)
            self$.addOption(private$..desc)
            self$.addOption(private$..plotPP)
            self$.addOption(private$..plotPPAddInfo)
            self$.addOption(private$..plotRobust)
            self$.addOption(private$..plotRobustAddInfo)
            self$.addOption(private$..plotSeq)
            self$.addOption(private$..plotSeqRobust)
            self$.addOption(private$..plotDesc)
            self$.addOption(private$..plotDescCI)
            self$.addOption(private$..missing)
            self$.addOption(private$..priorType)
            self$.addOption(private$..priorWidth)
            self$.addOption(private$..infoShape)
            self$.addOption(private$..infoCL)
            self$.addOption(private$..infoCS)
            self$.addOption(private$..infoNL)
            self$.addOption(private$..infoNS)
            self$.addOption(private$..infoTL)
            self$.addOption(private$..infoTS)
            self$.addOption(private$..infoTDf)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        hypothesis = function() private$..hypothesis$value,
        bfType = function() private$..bfType$value,
        desc = function() private$..desc$value,
        plotPP = function() private$..plotPP$value,
        plotPPAddInfo = function() private$..plotPPAddInfo$value,
        plotRobust = function() private$..plotRobust$value,
        plotRobustAddInfo = function() private$..plotRobustAddInfo$value,
        plotSeq = function() private$..plotSeq$value,
        plotSeqRobust = function() private$..plotSeqRobust$value,
        plotDesc = function() private$..plotDesc$value,
        plotDescCI = function() private$..plotDescCI$value,
        missing = function() private$..missing$value,
        priorType = function() private$..priorType$value,
        priorWidth = function() private$..priorWidth$value,
        infoShape = function() private$..infoShape$value,
        infoCL = function() private$..infoCL$value,
        infoCS = function() private$..infoCS$value,
        infoNL = function() private$..infoNL$value,
        infoNS = function() private$..infoNS$value,
        infoTL = function() private$..infoTL$value,
        infoTS = function() private$..infoTS$value,
        infoTDf = function() private$..infoTDf$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value),
    private = list(
        ..pairs = NA,
        ..hypothesis = NA,
        ..bfType = NA,
        ..desc = NA,
        ..plotPP = NA,
        ..plotPPAddInfo = NA,
        ..plotRobust = NA,
        ..plotRobustAddInfo = NA,
        ..plotSeq = NA,
        ..plotSeqRobust = NA,
        ..plotDesc = NA,
        ..plotDescCI = NA,
        ..missing = NA,
        ..priorType = NA,
        ..priorWidth = NA,
        ..infoShape = NA,
        ..infoCL = NA,
        ..infoCS = NA,
        ..infoNL = NA,
        ..infoNS = NA,
        ..infoTL = NA,
        ..infoTS = NA,
        ..infoTDf = NA,
        ..plotWidth = NA,
        ..plotHeight = NA)
)

bttestPSResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Paired Samples T-Test",
                clearWith=list(
                    "pairs",
                    "missing"))}))

bttestPSBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestPSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsq',
                name = 'bttestPS',
                version = c(1,0,0),
                options = options,
                results = bttestPSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bayesian Paired Samples T-Test
#'
#' 
#' @param data the data as a data frame
#' @param pairs a list of lists specifying the pairs of measurement in
#'   \code{data}
#' @param hypothesis .
#' @param bfType .
#' @param desc .
#' @param plotPP .
#' @param plotPPAddInfo .
#' @param plotRobust .
#' @param plotRobustAddInfo .
#' @param plotSeq .
#' @param plotSeqRobust .
#' @param plotDesc .
#' @param plotDescCI .
#' @param missing .
#' @param priorType .
#' @param priorWidth .
#' @param infoShape .
#' @param infoCL .
#' @param infoCS .
#' @param infoNL .
#' @param infoNS .
#' @param infoTL .
#' @param infoTS .
#' @param infoTDf .
#' @param plotWidth .
#' @param plotHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
bttestPS <- function(
    data,
    pairs,
    hypothesis = "different",
    bfType = "BF10",
    desc = FALSE,
    plotPP = FALSE,
    plotPPAddInfo = TRUE,
    plotRobust = FALSE,
    plotRobustAddInfo = TRUE,
    plotSeq = FALSE,
    plotSeqRobust = FALSE,
    plotDesc = FALSE,
    plotDescCI = 95,
    missing = "perAnalysis",
    priorType = "default",
    priorWidth = 0.707,
    infoShape = "cauchy",
    infoCL = 0,
    infoCS = 0.707,
    infoNL = 0,
    infoNS = 0.707,
    infoTL = 0,
    infoTS = 0.707,
    infoTDf = 1,
    plotWidth = 320,
    plotHeight = 240) {

    if ( ! requireNamespace('jmvcore'))
        stop('bttestPS requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- bttestPSOptions$new(
        pairs = pairs,
        hypothesis = hypothesis,
        bfType = bfType,
        desc = desc,
        plotPP = plotPP,
        plotPPAddInfo = plotPPAddInfo,
        plotRobust = plotRobust,
        plotRobustAddInfo = plotRobustAddInfo,
        plotSeq = plotSeq,
        plotSeqRobust = plotSeqRobust,
        plotDesc = plotDesc,
        plotDescCI = plotDescCI,
        missing = missing,
        priorType = priorType,
        priorWidth = priorWidth,
        infoShape = infoShape,
        infoCL = infoCL,
        infoCS = infoCS,
        infoNL = infoNL,
        infoNS = infoNS,
        infoTL = infoTL,
        infoTS = infoTS,
        infoTDf = infoTDf,
        plotWidth = plotWidth,
        plotHeight = plotHeight)

    analysis <- bttestPSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
